import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

export interface PDFExportTemplateProps {
    chatTitle: string;
    messages: any[];
}

export const PDFExportTemplate = React.forwardRef<HTMLDivElement, PDFExportTemplateProps>(
    ({ chatTitle, messages }, ref) => {
        return (
            <div ref={ref} className="p-12 font-sans bg-white text-black print:p-10 w-full">
                {/* Header Section */}
                <div className="flex flex-col border-b border-gray-200 pb-6 mb-8">
                    <h1 className="text-3xl font-bold text-black mb-2 tracking-tight">DUO AI</h1>
                    <h2 className="text-xl font-semibold text-gray-800">{chatTitle}</h2>
                    <p className="text-sm text-gray-500 mt-2">
                        Exported on {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                    </p>
                </div>

                {/* Messages Section */}
                <div className="flex flex-col gap-8">
                    {messages.map((msg, idx) => (
                        <div key={idx} className={`flex flex-col ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
                            <div className="flex flex-col gap-1 w-full max-w-[85%]">
                                <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1 px-1">
                                    {msg.role === 'user' ? 'You' : 'DUO AI'}
                                </span>
                                <div 
                                    className={`text-[14px] leading-relaxed p-4 rounded-2xl ${
                                        msg.role === 'user' 
                                            ? 'bg-gray-100 text-black rounded-tr-sm self-end border border-gray-200' 
                                            : 'bg-white text-black border border-gray-200'
                                    }`}
                                >
                                    <div className="prose prose-sm prose-black max-w-none prose-p:leading-relaxed prose-pre:bg-gray-100 prose-pre:text-black">
                                        {msg.role === 'user' ? (
                                            msg.content
                                        ) : (
                                            <ReactMarkdown remarkPlugins={[remarkGfm]}>
                                                {msg.content}
                                            </ReactMarkdown>
                                        )}
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Footer Section */}
                <div className="mt-16 pt-6 border-t border-gray-200 text-center">
                    <p className="text-xs text-gray-400">
                        Generated by DUO Finance — Your Household AI Assistant
                    </p>
                </div>
            </div>
        );
    }
);

PDFExportTemplate.displayName = 'PDFExportTemplate';
